#!/bin/sh
# qemu9

case $# in
1|2)
	;;
*)
	echo "usage: qemu9 img [iso]" 1>&2
	exit 1
	;;
esac

img=$1
iso=$2

qemu="qemu-system-x86_64 -cpu host -enable-kvm -m 1G \
	-net nic,model=virtio,macaddr=52:54:ca:fe:ba:be -net vde \
	-device virtio-scsi-pci,id=scsi \
	-drive if=none,id=vd0,file=$img \
	-device scsi-hd,drive=vd0"

if [ -n "$iso" ]
then
	qemu="$qemu -drive if=none,id=vd1,file=$iso \
	-device scsi-cd,drive=vd1,bootindex=0"
fi

exec $qemu
